### ISSUE TITLE
初始化数据库命令存在错误

### ISSUE THREAD

**Issue by Wjlljw** [bytesc/django_management_system_template#1]
![image](https://github.com/bytesc/Django_Management_System_template/assets/100983951/1ccfd43f-eca7-4971-bbfb-b12ac1dc76c7)
第二条命令存在错误，正确的命令应该是：
`python manage.py migrate`

**Comment by bytesc** [comment]
已修改相关问题，感谢您的支持🤝
@Wjlljw
