### ISSUE TITLE
错误求助

### ISSUE THREAD

**Issue by huangdiwang** [bytesc/django_management_system_template#3]
ycharmProjects\pythonProject\study_djano> python manage.py makemigrations
D:\python\python.exe: can't open file 'D:\\PycharmProjects\\pythonProject\\study_djano\\manage.py': [Errno 2] No such file or directory
这是什么意思呢

**Comment by bytesc** [comment]
@huangdiwang 
请检查你的`D:\PycharmProjects\pythonProject\study_djano\manage.py` 这个路径下是否有 `manage.py` 这个文件？
