### ISSUE TITLE
question

### ISSUE THREAD

**Issue by huangdiwang** [bytesc/django_management_system_template#4]
大哥请问如何添加新的管理员

**Comment by bytesc** [comment]
<img width="576" alt="Snipaste_2023-12-13_19-59-02" src="https://github.com/bytesc/Django_Management_System_template/assets/103081365/f292152a-5430-400b-879d-e306e7e03194">

**Comment by huangdiwang** [comment]
我添加了但是在登录的时候不行，adm_obj = MyAdmin.objects.filter(**form.cleaned_data).first()这行代码是匹配第一个，所以登录其他管理员就会说账户密码错误，大佬

**Comment by bytesc** [comment]
这行代码是按照登录的时候输入的用户名和密码，查找用户名和密码都匹配的第一个。

**Comment by huangdiwang** [comment]
好的大佬明白了
